### PR TITLE
Coordinator index changes

### PR DESCRIPTION
**Pull request by aniarya82**

### CODE REVIEW

**Comment by icyflame** [comment]
@aniarya82 
1. Please upload a screenshot of the output.

**Comment by icyflame** [comment]
@aniarya82 
1. This is the same issue that we had faced that day:

image

Please fix this by referring to the code in the home page of the student member, where this has been properly implemented.

**Comment by aniarya82** [comment]
Dude we talked about this problem on the day of farewell treat and i don't remember us reaching to an solution that day..!! :/

**Comment by aniarya82** [comment]
look the search thing was resolved but the tie thing wasn't 
as i added this line
screen shot 2015-05-07 at 2 25 49 pm
i got this nil.class error
screen shot 2015-05-07 at 2 26 07 pm

**Comment by icyflame** [comment]
Did you copy the code verbatim from the student member home page?

**Comment by aniarya82** [comment]
verbatim..???

**Comment by icyflame** [comment]
Word-to-word.

**Comment by aniarya82** [comment]
see your self 
i added the image

**Comment by icyflame** [comment]
@aniarya82 
Okay, I will have to copy the code from the student thing myself. I will do it later today/tonight. Please work on the changes requested in the other PR you sent (#28)

**Comment by aniarya82** [comment]
the travis build..???

**Pull request merged**
