### PR TITLE
coordinator profile page updated

### PR DESCRIPTION
**Pull request by aniarya82**

### CODE REVIEW

**Comment by icyflame** [comment]
@aniarya82 
Some snapshots will be extremely helpful. So, please upload the same onto this conversation.

**Comment by aniarya82** [comment]
screen shot 2015-04-24 at 3 54 55 am
i am unable to figure out the TieAlumniWithStudentMenber thing

**Comment by icyflame** [comment]
@aniarya82 
Great work!

These are some first impressions:

- Please remove the big two buttons at the top of the page, they seem to be out of place. I want to have those buttons, but we will have to figure out a better place.
- Move the row consisting of the total students and total alumni to the top of of the table. (Above the table)
- Please make the table headers bold. This will ensure that they stand out.

And as for the Travis Build, please don't worry about that. The setup files are not there on this branch yet. I will integrate them into this particular branch after these set of changes.

**Comment by aniarya82** [comment]
well those are not button, they are just labels

and to display profile page, i added the show path to the place in nabber where you display signed in as

**Comment by icyflame** [comment]
Yes, that's fine. I don't think the labels are necessary, if required, you
can put them in the navbar. That will be better, as that would not take too
much space, and neither would it seem out of place. And a colored label in
the navbar will tell the user the type of privileges that he/she is in
immediately. What do you think?

**Comment by aniarya82** [comment]
thats better idea i guess, so what color u want..???

i say: 
blue: student member
red: coordinator

what u say.??

**Comment by icyflame** [comment]
@aniarya82 
of course! The colors are upto you, they don't matter a lot since this is not being deployed to the public. :+1:

**Comment by aniarya82** [comment]
okay check the files, and merge the pull request

**Comment by icyflame** [comment]
@aniarya82 
Thanks! I will look into this, and merge the PR. (Probably today evening.)

**Comment by aniarya82** [comment]
peace. 

I'll start working on show pages for coordinator as well as student member .

**Comment by icyflame** [comment]
@aniarya82 :+1: 

Will you be working on top of this branch?

**Comment by aniarya82** [comment]
nah created a new one

**Comment by aniarya82** [comment]
i'll update my master then start working on new from there on

**Comment by icyflame** [comment]
Hmm, Yes. These changes are indeed independent of them. You would simply have to edit `show.html.erb` files in both the cases. Is that what you are planning on doing?

**Comment by aniarya82** [comment]
yup

**Comment by icyflame** [comment]
@aniarya82 
Peace. Go ahead! I am sorry about the delay in merging this PR, End terms! 

And you may also want to configure Travis CI. (It's pretty simply: `Sign Up`, `Go to the profile and activate your repo`. Do it if you get time.)

**Comment by aniarya82** [comment]
okay i look into it..!!

**Comment by aniarya82** [comment]
But if i also configure the travis thing..... the config file will be
changed right

On Fri, Apr 24, 2015 at 11:03 AM, Siddharth Kannan <notifications@github.com
> wrote:

> @aniarya82 <https://github.com/aniarya82>
> Peace. Go ahead! I am sorry about the delay in merging this PR, End terms!
>
> And you may also want to configure Travis CI. (It's pretty simply: Sign Up,
> Go to the profile and activate your repo. Do it if you get time.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/icyflame/networking-rails/pull/21#issuecomment-95806157>
> .
>



-- 

*Regards,*

*Hiten Chowdhary*

*Undergraduate Student*

*Department of Mathematics*

*IIT Kharagpur*

*Ph: +919800111032*

**Comment by icyflame** [comment]
@aniarya82 
No, the travisCI config file remains unchanged.

**Comment by aniarya82** [comment]
how come two different repo will have same config file

**Comment by icyflame** [comment]
Well, the travis Config file is looked up from the repo itself. So, there's nothing `repo specific` in my current config file. Check out the `.travis.yml` file at `/`. You will know for yourself.

**Comment by aniarya82** [comment]
i already checked...it has some very long api_key

**Comment by aniarya82** [comment]
like now i have puller your origin into my localhost, so i have that config.yml file already

So now when i m creating an account on travis CI i guess i don't need to add the config file aagain

**Comment by icyflame** [comment]
@aniarya82 
These are some of my observations:

- The assigned to column is not properly populated. Check out the `TieAlumniWithStudent` model, and implement this.

**Comment by aniarya82** [comment]
Arey I am not able to figure it out

I am trying to search student I'd in tie database with help of alumni I'd
but error says no student member tag

Help me out here

And another this student to alumni relation should be one to many right.

But in db only one alum can be assigned to one student

**Comment by icyflame** [comment]
Hey, Thanks for pointing that out m surprisingly, it was working on my PC,
but it isn't working on Heroku either.

I will fix this and get back to you.

**Comment by aniarya82** [comment]
i'll saw fix and rebase the branch to master

**Comment by icyflame** [comment]
@aniarya82 
What was that? And we can move to slack, this conversation is getting too big!

**Comment by icyflame** [comment]
@aniarya82 
This branch was rebased onto the latest master.
A new PR will be opened.

Closing this now!

**Pull request closed without merging**
