### PR TITLE
profile page for student member created

### PR DESCRIPTION
**Pull request by aniarya82**

### CODE REVIEW

**Comment by aniarya82** [comment]
screen shot 2015-04-18 at 6 12 24 pm

**Comment by aniarya82** [comment]
Well now i saw the other branch, but why is that issue still open..??

**Comment by icyflame** [comment]
@aniarya82 Your design is very good! Great work! I am still working on that, so, that issue was open.

I will merge it now!

What you can do, is that, after I merge, take your code, and simply put my code for rendering all the alloted alums into the list. Or, If you have written a custom rendering alums code, then, feel free to open a PR after I do, then we can discuss there!

**Comment by icyflame** [comment]
@aniarya82 
I don't think we need to follow the two column approach here, because we will have a lot of data, man!

So, I guess, we should have the labels (Student, and student1) but we don't really need the second column. Anyways, let's keep this on hold for some time now.

The coordinator thing (#8) is far more important.

**Pull request closed without merging**
