### PR TITLE
Viewall controller

### PR DESCRIPTION
**Pull request by aniarya82**

### CODE REVIEW

**Comment by icyflame** [comment]
@aniarya82 
1. Please see why the TravisCI build is failing. AFAIK, this is because of a problem in the files inside the directory `test/`. See this, and confirm what the problem was and how you solved it.

2. The `dataTables` CSS files that are there in the Files Changed tab. Please tell me if they are necessary.

3. Post a screenshot of the working viewall page here.

**Comment by aniarya82** [comment]
screen shot 2015-05-04 at 9 27 41 pm
yeah the complete directory of js and css file is neccesary

**Comment by icyflame** [comment]
@aniarya82 
1. The screen looks good. Please remove the default text that is there. We don't need that. (`Viewall#index`, etc)

2. For dataTables, I was going through the documentation and didn't come across the requirement of copying all those files into the CSS directory. Documentation: https://github.com/rweng/jquery-datatables-rails
(I insist on researching this because these files will make our site unnecessarily heavy. Please go through the documentation and tell me if that is absolutely essential.)

**Comment by icyflame** [comment]
@aniarya82 
I would like to retract on the issue.

Were you talking about this: https://github.com/rweng/jquery-datatables-rails#responsive-installation

The generator came up with all those files?

**Comment by aniarya82** [comment]
yup exactly i needs those files

**Comment by icyflame** [comment]
@aniarya82 Thanks a lot, that's fine then. We have to go along with the files. 

Please remove the two default lines and push a commit. I will then check build locally and get back to the discussion here.

**Comment by aniarya82** [comment]
screen shot 2015-05-04 at 9 35 15 pm
This peace..???

**Comment by icyflame** [comment]
@aniarya82 

I would actually have the text changed slightly.

`Viewall controller`-> `Complete Alumni Database`.
Please also center align this text. That would look better.

(They don't need to know about the controller jargon, as they would not understand it.)

**Comment by aniarya82** [comment]
screen shot 2015-05-04 at 9 38 57 pm

**Comment by icyflame** [comment]
@aniarya82 
The front end is fine. :+1: 

Please integrate the `before_action` thing in the controller, so only people who are signed in are able to view this page.

**Comment by icyflame** [comment]
@aniarya82 
1. Build checked. There are errors that are yet to be fixed:

image

This image came up when I was trying to access `/viewall/index/`. Please look into this.

**Comment by icyflame** [comment]
@aniarya82 
Please check the above comment, that is independent of the travis build. You need not work on the travis build, just make sure that the viewall page is rendering properly on your computer.

**Comment by aniarya82** [comment]
I copied the code exactly from the student member but i is not working here ...donno why...!!

**Comment by icyflame** [comment]
@aniarya82 
Was the dataTables gem working on your machine?

I just `bundle install` ed it, and tried it in the browser, but it's not working. Any other special things to be done?

P.S. Also, why did you use the gem? The CDN's are far easier to use.

**Pull request merged**
